language: java
sudo: required
dist: trusty
before_install:
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
  - env: JDK='Oracle JDK 10'
    install: ". ./install-jdk.sh -F 10 -L BCL"
before_script:
- docker-compose up -d
env:
  global:
  - secure: i5td07j8SrT+SSLAX+YPBYWWBcUwgtGTnZbpw2pPPK65H7+yFtRA9JzC3ZcwujIqqsEt7Wm7s/2h8Pm8YXHoTJaqVDcC41lzNTUQaQPkJwRmwPavsp6YP8YheK1j8jLxXpHNjLqNCr9+AE4UcIIocdzuDG1lSFYOQzJ4SPqExvxR8aIhfyE+uF8gxp7U0nQHiBapo7z0RyNTFf0nbZqhy9uCx0nTCLiKSLspnKIS59zhhhu093Ezmo4noTu6PZDT83R70FyV2i5kJR0UvonKeLBVaJ7e2DbnUJdHTJ+D2vlUIpWg85vDVDjh5OXSxo0TYCYsLAlJOI2DRe8buTVspS/cPDmMA9oMvXJyLsOcj8dvUmXyftkXId8DXVmMMoby9utSvjQEdqMN6WTcVLy7z/TlSEcFU/rcp2Q1iIZSLrFJkUBp7gDcbJ6IVOkiU1+1pIYzzJGnDRIkmvwM7Zv61knzsvk5rx/uNHJXwnQKCNzn2MCyhffNEjDafEbfIlE1KXS+FwJS9Ne+VvjTUkj7dSWYKnUncS3fcM2uipdIXjd0Eli3lUj1UggM8nyBWDxewflqEQGgwm7wHZ6kGXSrPgEWOvaS79mxLgYRkXJGQ5TJunGntqJOOdLGJGoxmzPlYARJOGcvx7D5B3WW8DHX6ATiFckhkYiw59wAW/li8HI=
  - secure: XljIbFkVEXONWWpst2E0i7GbjXETBF3yCtt89x2OMRYIHJXxAcar2GCX2tjpy2scsYUJ0yhIpqf9ULYtW1iQE7nT9GDIL8rQfqddNbQQOwClQ2NlVO2PDzdoDmy0l6QayrwRMs7KgAi0ZRzwoK3YmsdS+eQOefwss3Yz7OvxZ4wWjxnGHVTEfSK5N56q00G8+IaOw3Iabh32d6qrsgX+rBQY7CXCfC7OkGFlAX7gphfMfTGyIySR/G722vpQq+APyXgtyl0YY13uF4g/3Vf7xkjhjWb9KRBCaY/XDIrIRIlZizKPBnSVeRubRpaQkf5RSaBso6Hb5VRgIofzOoW4jU2ySDk8v9qaVTx9V9bVLKr/fxzHBPvHBTLsOMBj/A7kvhWAL5joFAlucvohF8FqpZqKmz0Mg8JYk+rp55X6s4IsHvzKEqoVYPLYzxWv3uMVsgjZkb4CMvnZkfxVLO6ZNVNA2irhscVoCPrbaVXukAY3q6LDyD3pIIWSiwT4kOsTtywl2FESvOoqZzMtybJE7+ix8jjvoHSl8DsUaNPsvIQFiI6iBl9ZN7T+3oSfUbHcArlfzg7gsVCZdf64+M4HpuzqkCfS1PPzSjvRYn5Ko1avLm83I/lK4+c9tNu/UADqeIfcNqAkIMopJaa80YeKINAGrZr4qGl4EvgeYweT+vs=
after_success:
- ./gradlew assemble
- docker -v
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- set +e
- export REPO=aista/form-expert-warehouse
- docker build -t $REPO:$TRAVIS_TAG -t $REPO:latest .
- bash <(curl -s https://codecov.io/bash)
- docker push $REPO